### ISSUE TITLE
Compliance: Installer X paquets en même temps

### ISSUE THREAD

**Issue by naparuba** [naparuba/kunai#69]
```
#   Packages install, avec une boucle for
name: Install JDK, PostgreSQL, pip
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ jdk_version }}"
    - postgresql-server
    - postgresql-contrib
    - python-pip
    - unzip

```
