### ISSUE TITLE
COMPLIANCE: service mais avec un rétat restart

### ISSUE THREAD

**Issue by naparuba** [naparuba/kunai#84]
```
# Service mais avec un état RESTART
- name: Start and enable tomcat8
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: tomcat8
```
